# config/panel/page_solar.yaml
id: page_solar
widgets:
  - obj:
      width: 100%
      styles: page_bg_style
      pad_all: 15
      layout: { type: flex, flex_flow: COLUMN }
      widgets:
        # --- СЕКЦИЯ: СОЛНЦЕ ---
        - label: { text: "СОНЦЕ", styles: group_label_style }
        - obj:
            width: 100%
            bg_opa: TRANSP
            styles: group_style
            layout: { type: flex, flex_flow: ROW }
            widgets:
              - obj:
                  styles: card_style
                  widgets:
                    - label: { text: "\U000F0410", x: 15, y: 15, text_font: mdi_20, text_color: 0x0A84FF}
                    - label: { text: "Вольтаж панелей", x: 45, y: 18, text_font: roboto_14, text_color: 0xAAAAAA }
                    - label: { id: solar_voltage, text: "0 V", align: BOTTOM_LEFT, x: 15, y: -15 }
              - obj:
                  styles: card_style
                  widgets:
                    - label: { text: "\U000F0410", x: 15, y: 15, text_font: mdi_20, text_color: 0x0A84FF}
                    - label: { text: "Вольтаж мережі F1", x: 45, y: 18, text_font: roboto_14, text_color: 0xAAAAAA }
                    - label: { id: solar_grid_voltage_f1, text: "0 V", align: BOTTOM_LEFT, x: 15, y: -15 }
              - obj:
                  x: 20
                  styles: card_style
                  widgets:
                    - label: { text: "\U000F0079", x: 15, y: 15, text_font: mdi_20, text_color: 0x0A84FF}
                    - label: { text: "Вольтаж батареї", x: 45, y: 18, text_font: roboto_14, text_color: 0xAAAAAA }
                    - label: { id: solar_battery_voltage, text: "0 V", align: BOTTOM_LEFT, x: 15, y: -15 }
        # --- СЕКЦИЯ: СЕТЬ ---
        - label: { text: "МЕРЕЖА", styles: group_label_style }
        - obj:
            width: 100%
            height: 200
            bg_opa: TRANSP
            styles: group_style
            layout: { type: flex, flex_flow: ROW }
            widgets:
              - obj:
                  styles: card_style_triple
                  widgets:
                    - label: { text: "\U000F07D0", x: 15, y: 15, text_font: mdi_20, text_color: 0x0A84FF}
                    - label: { text: "Вольтаж фаз", x: 45, y: 18, text_font: roboto_14, text_color: 0xAAAAAA }
                    - label: { id: power_voltage_f1, text: "F1: 0 V", align: BOTTOM_LEFT, x: 15, y: -62 }
                    - label: { id: power_voltage_f2, text: "F2: 0 V", align: BOTTOM_LEFT, x: 15, y: -38 }
                    - label: { id: power_voltage_f3, text: "F3: 0 V", align: BOTTOM_LEFT, x: 15, y: -15 }
              - obj:
                  styles: card_style_triple
                  widgets:
                    - label: { text: "\U000F07D0", x: 15, y: 15, text_font: mdi_20, text_color: 0x0A84FF}
                    - label: { text: "Потужність фаз", x: 45, y: 18, text_font: roboto_14, text_color: 0xAAAAAA }
                    - label: { id: power_power_f1, text: "F1: 0 W", align: BOTTOM_LEFT, x: 15, y: -62 }
                    - label: { id: power_power_f2, text: "F2: 0 W", align: BOTTOM_LEFT, x: 15, y: -38 }
                    - label: { id: power_power_f3, text: "F3: 0 W", align: BOTTOM_LEFT, x: 15, y: -15 }
              - obj:
                  styles: card_style_triple
                  widgets:
                    - label: { text: "\U000F07D0", x: 15, y: 15, text_font: mdi_20, text_color: 0x0A84FF}
                    - label: { text: "Ток мережі", x: 45, y: 18, text_font: roboto_14, text_color: 0xAAAAAA }
                    - label: { id: power_current_f1, text: "F1: 0 A", align: BOTTOM_LEFT, x: 15, y: -62 }
                    - label: { id: power_current_f2, text: "F2: 0 A", align: BOTTOM_LEFT, x: 15, y: -38 }
                    - label: { id: power_current_f3, text: "F3: 0 A", align: BOTTOM_LEFT, x: 15, y: -15 }
              - obj:
                  styles: card_style_triple
                  widgets:
                    - label: { text: "\U000F07D0", x: 15, y: 15, text_font: mdi_20, text_color: 0x0A84FF}
                    - label: { text: "Споживання будинку", x: 45, y: 18, text_font: roboto_14, text_color: 0xAAAAAA }
                    - label: { id: power_total_power, text: "0 kWh", align: BOTTOM_LEFT, x: 15, y: -62 }
                    - label: { id: power_total_current, text: "0 A", align: BOTTOM_LEFT, x: 15, y: -38 }
